import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { CandidateStructuredData, job as defaultJob } from '@rr/shared';

const root = path.basename(process.cwd()) === 'api' ? path.resolve(process.cwd(), '../..') : process.cwd();
const dataDir = path.join(root, 'data');
const uploadDir = path.join(dataDir, 'uploads');
fs.mkdirSync(uploadDir, { recursive: true });
const dbPath = process.env.DATABASE_URL?.replace(/^file:/, '') || path.join(dataDir, 'resume-review.sqlite');
fs.mkdirSync(path.dirname(dbPath), { recursive: true });
export const db = new DatabaseSync(dbPath);
db.exec('PRAGMA foreign_keys = ON');
db.exec(`CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, status TEXT NOT NULL, rubric_version TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, job_id TEXT REFERENCES jobs(id), original_filename TEXT NOT NULL, stored_filename TEXT NOT NULL, file_path TEXT NOT NULL, file_hash TEXT NOT NULL, page_count INTEGER, raw_text TEXT NOT NULL, normalized_text TEXT NOT NULL, processing_status TEXT NOT NULL, processing_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS candidates (id TEXT PRIMARY KEY, document_id TEXT NOT NULL UNIQUE REFERENCES documents(id) ON DELETE CASCADE, candidate_name TEXT, email TEXT, phone TEXT, location TEXT, summary TEXT, structured_data TEXT NOT NULL, extraction_status TEXT NOT NULL, extraction_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS fit_reviews (id TEXT PRIMARY KEY, job_id TEXT REFERENCES jobs(id), job_title TEXT, job_description TEXT NOT NULL, candidate_ids TEXT NOT NULL, evaluation_result TEXT NOT NULL, model_name TEXT NOT NULL, prompt_version TEXT NOT NULL, created_at TEXT NOT NULL);`);

const hasColumn = (table: string, column: string) => (db.prepare(`PRAGMA table_info(${table})`).all() as Array<{ name: string }>).some(x => x.name === column);
if (!hasColumn('documents', 'job_id')) db.exec('ALTER TABLE documents ADD COLUMN job_id TEXT REFERENCES jobs(id)');
if (!hasColumn('fit_reviews', 'job_id')) db.exec('ALTER TABLE fit_reviews ADD COLUMN job_id TEXT REFERENCES jobs(id)');
const now = () => new Date().toISOString();
const timestamp = now();
db.prepare('INSERT OR IGNORE INTO jobs (id,title,description,status,rubric_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(defaultJob.id, defaultJob.title, defaultJob.description, defaultJob.status, defaultJob.rubricVersion, timestamp, timestamp);
db.prepare('UPDATE documents SET job_id=? WHERE job_id IS NULL').run(defaultJob.id);
db.prepare('UPDATE fit_reviews SET job_id=? WHERE job_id IS NULL').run(defaultJob.id);
db.exec('CREATE UNIQUE INDEX IF NOT EXISTS documents_job_hash ON documents(job_id, file_hash)');

export type JobRow = { id: string; title: string; description: string; status: string; rubric_version: string; created_at: string; updated_at: string };
export type DocumentRow = { id:string; job_id:string; original_filename:string; stored_filename:string; file_path:string; file_hash:string; page_count:number|null; raw_text:string; normalized_text:string; processing_status:string; processing_error:string|null; created_at:string; updated_at:string; job_title?:string };
export type CandidateRow = {id:string;job_id:string;document_id:string;candidate_name:string|null;email:string|null;phone:string|null;location:string|null;summary:string|null;structured_data:string;extraction_status:string;extraction_error:string|null;created_at:string;updated_at:string;original_filename?:string;normalized_text?:string;most_recent_position?:string|null};
export type FitReviewRow = {id:string;job_id:string;job_title:string|null;job_description:string;candidate_ids:string;evaluation_result:string;model_name:string;prompt_version:string;created_at:string};
export const fileHash=(buffer:Buffer)=>crypto.createHash('sha256').update(buffer).digest('hex');
export function safeFilename(filename:string){const base=path.basename(filename).replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'resume.pdf';return base.toLowerCase().endsWith('.pdf')?base:`${base}.pdf`;}
export function listJobs(){return db.prepare('SELECT * FROM jobs ORDER BY created_at DESC').all() as unknown as JobRow[];}
export function getJob(id:string){return db.prepare('SELECT * FROM jobs WHERE id=?').get(id) as JobRow|undefined;}
export function createJob(input:{title:string;description:string;status?:string}){const id=`job-${crypto.randomUUID()}`, time=now();db.prepare('INSERT INTO jobs (id,title,description,status,rubric_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(id,input.title,input.description,input.status||'Open','v1.0',time,time);return getJob(id)!;}
export function getDocument(id:string){return db.prepare('SELECT d.*, j.title as job_title FROM documents d JOIN jobs j ON j.id=d.job_id WHERE d.id = ?').get(id) as DocumentRow|undefined;}
export function listDocuments(jobId?:string){const query=jobId?'SELECT d.*, j.title as job_title FROM documents d JOIN jobs j ON j.id=d.job_id WHERE d.job_id=? ORDER BY d.created_at DESC':'SELECT d.*, j.title as job_title FROM documents d JOIN jobs j ON j.id=d.job_id ORDER BY d.created_at DESC';return (jobId?db.prepare(query).all(jobId):db.prepare(query).all()) as unknown as DocumentRow[];}
export function getCandidate(id:string){return db.prepare('SELECT c.*, d.job_id, d.original_filename, d.normalized_text FROM candidates c JOIN documents d ON d.id=c.document_id WHERE c.id=?').get(id) as CandidateRow|undefined;}
export function listCandidates(jobId?:string){const query=jobId?'SELECT c.*, d.job_id, d.original_filename, d.normalized_text, json_extract(c.structured_data, \'$.experience[0].title\') as most_recent_position FROM candidates c JOIN documents d ON d.id=c.document_id WHERE d.job_id=? ORDER BY c.created_at DESC':'SELECT c.*, d.job_id, d.original_filename, d.normalized_text, json_extract(c.structured_data, \'$.experience[0].title\') as most_recent_position FROM candidates c JOIN documents d ON d.id=c.document_id ORDER BY c.created_at DESC';return (jobId?db.prepare(query).all(jobId):db.prepare(query).all()) as unknown as CandidateRow[];}
export function getCandidates(ids:string[],jobId?:string){if(!ids.length)return [];const marks=ids.map(()=>'?').join(',');const suffix=jobId?' AND d.job_id=?':'';const params=jobId?[...ids,jobId]:ids;return db.prepare(`SELECT c.*, d.job_id, d.original_filename, d.normalized_text FROM candidates c JOIN documents d ON d.id=c.document_id WHERE c.id IN (${marks})${suffix}`).all(...params) as unknown as CandidateRow[];}
export function createDocument(input:{jobId:string;originalFilename:string;buffer:Buffer;pageCount:number;rawText:string;normalizedText:string;structuredData:CandidateStructuredData;extractionStatus?:string;extractionError?:string|null}){const hash=fileHash(input.buffer);const existing=db.prepare('SELECT id FROM documents WHERE job_id=? AND file_hash=?').get(input.jobId,hash) as {id:string}|undefined;if(existing)return {duplicate:true,documentId:existing.id};const id=`doc-${crypto.randomUUID()}`, stored=`${id}-${safeFilename(input.originalFilename)}`, filePath=path.join(uploadDir,stored), time=now();db.exec('BEGIN');try{fs.writeFileSync(filePath,input.buffer);db.prepare('INSERT INTO documents (id,job_id,original_filename,stored_filename,file_path,file_hash,page_count,raw_text,normalized_text,processing_status,processing_error,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,input.jobId,input.originalFilename,stored,filePath,hash,input.pageCount,input.rawText,input.normalizedText,'completed',null,time,time);const candidateId=`candidate-${crypto.randomUUID()}`;db.prepare('INSERT INTO candidates (id,document_id,candidate_name,email,phone,location,summary,structured_data,extraction_status,extraction_error,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run(candidateId,id,input.structuredData.candidate_name,input.structuredData.email,input.structuredData.phone,input.structuredData.location,input.structuredData.summary,JSON.stringify(input.structuredData),input.extractionStatus||'completed',input.extractionError||null,time,time);db.exec('COMMIT');return {duplicate:false,documentId:id,candidateId};}catch(error){db.exec('ROLLBACK');try{fs.unlinkSync(filePath)}catch{};throw error;}}
export function deleteDocument(id:string){const doc=getDocument(id);if(!doc)return false;db.prepare('DELETE FROM documents WHERE id=?').run(id);try{fs.unlinkSync(doc.file_path)}catch{};return true;}
export function deleteJob(id:string){const job=getJob(id);if(!job)return false;const documents=listDocuments(id);db.exec('BEGIN');try{db.prepare('DELETE FROM fit_reviews WHERE job_id=?').run(id);db.prepare('DELETE FROM documents WHERE job_id=?').run(id);db.prepare('DELETE FROM jobs WHERE id=?').run(id);db.exec('COMMIT');for(const document of documents){try{fs.unlinkSync(document.file_path)}catch{}}return true;}catch(error){db.exec('ROLLBACK');throw error;}}
export function updateDocumentContent(id:string,input:{pageCount:number;rawText:string;normalizedText:string;structuredData:CandidateStructuredData;status:string;error?:string|null}){const time=now();db.prepare('UPDATE documents SET page_count=?,raw_text=?,normalized_text=?,processing_status=?,processing_error=?,updated_at=? WHERE id=?').run(input.pageCount,input.rawText,input.normalizedText,input.status,input.error||null,time,id);db.prepare('UPDATE candidates SET candidate_name=?,email=?,phone=?,location=?,summary=?,structured_data=?,extraction_status=?,extraction_error=?,updated_at=? WHERE document_id=?').run(input.structuredData.candidate_name,input.structuredData.email,input.structuredData.phone,input.structuredData.location,input.structuredData.summary,JSON.stringify(input.structuredData),input.status,input.error||null,time,id);return getDocument(id);}
export function saveFitReview(input:{jobId:string;jobTitle:string|null;jobDescription:string;candidateIds:string[];result:unknown;modelName:string}){const id=`fit-${crypto.randomUUID()}`;db.prepare('INSERT INTO fit_reviews (id,job_id,job_title,job_description,candidate_ids,evaluation_result,model_name,prompt_version,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,input.jobId,input.jobTitle,input.jobDescription,JSON.stringify(input.candidateIds),JSON.stringify(input.result),input.modelName,'candidate-fit-v1',now());return getFitReview(id)!;}
export function listFitReviews(jobId?:string){const query=jobId?'SELECT * FROM fit_reviews WHERE job_id=? ORDER BY created_at DESC':'SELECT * FROM fit_reviews ORDER BY created_at DESC';return (jobId?db.prepare(query).all(jobId):db.prepare(query).all()) as unknown as FitReviewRow[];}
export function getFitReview(id:string){return db.prepare('SELECT * FROM fit_reviews WHERE id=?').get(id) as FitReviewRow|undefined;}
