import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { CandidateStructuredData, job as defaultJob } from '@rr/shared';

const root = path.basename(process.cwd()) === 'api' ? path.resolve(process.cwd(), '../..') : process.cwd();
const dataDir = path.join(root, 'data');
const uploadDir = path.join(dataDir, 'uploads');
fs.mkdirSync(uploadDir, { recursive: true });
const dbPath = process.env.DATABASE_URL?.replace(/^file:/, '') || path.join(dataDir, 'resume-review.sqlite');
fs.mkdirSync(path.dirname(dbPath), { recursive: true });
export const db = new DatabaseSync(dbPath);
db.exec('PRAGMA foreign_keys = ON');
db.exec(`CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, status TEXT NOT NULL, rubric_version TEXT NOT NULL, rubric TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, job_id TEXT REFERENCES jobs(id), original_filename TEXT NOT NULL, stored_filename TEXT NOT NULL, file_path TEXT NOT NULL, file_hash TEXT NOT NULL, page_count INTEGER, raw_text TEXT NOT NULL, normalized_text TEXT NOT NULL, processing_status TEXT NOT NULL, processing_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS candidates (id TEXT PRIMARY KEY, document_id TEXT NOT NULL UNIQUE REFERENCES documents(id) ON DELETE CASCADE, candidate_name TEXT, email TEXT, phone TEXT, location TEXT, summary TEXT, structured_data TEXT NOT NULL, extraction_status TEXT NOT NULL, extraction_error TEXT, current_status TEXT NOT NULL DEFAULT 'uploaded', status_updated_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS fit_reviews (id TEXT PRIMARY KEY, job_id TEXT REFERENCES jobs(id), job_title TEXT, job_description TEXT NOT NULL, candidate_ids TEXT NOT NULL, evaluation_result TEXT NOT NULL, model_name TEXT NOT NULL, prompt_version TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS candidate_status_history (id TEXT PRIMARY KEY, candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE, from_status TEXT, to_status TEXT NOT NULL, changed_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS candidate_fit_reviews (id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE, job_description TEXT NOT NULL, rubric TEXT, score INTEGER NOT NULL, rationale TEXT NOT NULL, evidence TEXT NOT NULL, strengths TEXT NOT NULL, gaps TEXT NOT NULL, model_name TEXT NOT NULL, prompt_version TEXT NOT NULL, created_at TEXT NOT NULL);`);

const hasColumn = (table: string, column: string) => (db.prepare(`PRAGMA table_info(${table})`).all() as Array<{ name: string }>).some(x => x.name === column);
if (!hasColumn('documents', 'job_id')) db.exec('ALTER TABLE documents ADD COLUMN job_id TEXT REFERENCES jobs(id)');
if (!hasColumn('fit_reviews', 'job_id')) db.exec('ALTER TABLE fit_reviews ADD COLUMN job_id TEXT REFERENCES jobs(id)');
if (!hasColumn('jobs', 'rubric')) db.exec('ALTER TABLE jobs ADD COLUMN rubric TEXT');
if (!hasColumn('candidates', 'current_status')) db.exec("ALTER TABLE candidates ADD COLUMN current_status TEXT NOT NULL DEFAULT 'uploaded'");
if (!hasColumn('candidates', 'status_updated_at')) db.exec("ALTER TABLE candidates ADD COLUMN status_updated_at TEXT NOT NULL DEFAULT ''");
const now = () => new Date().toISOString();
const timestamp = now();
db.prepare('INSERT OR IGNORE INTO jobs (id,title,description,status,rubric_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(defaultJob.id, defaultJob.title, defaultJob.description, defaultJob.status, defaultJob.rubricVersion, timestamp, timestamp);
db.prepare('UPDATE documents SET job_id=? WHERE job_id IS NULL').run(defaultJob.id);
db.prepare('UPDATE fit_reviews SET job_id=? WHERE job_id IS NULL').run(defaultJob.id);
db.prepare("UPDATE candidates SET status_updated_at=created_at WHERE status_updated_at='' OR status_updated_at IS NULL").run();
db.prepare("UPDATE candidates SET current_status='ready_for_review' WHERE extraction_status='completed' AND current_status='uploaded'").run();
db.exec("INSERT INTO candidate_status_history (id,candidate_id,from_status,to_status,changed_at) SELECT 'status-' || c.id,c.id,NULL,c.current_status,c.status_updated_at FROM candidates c WHERE NOT EXISTS (SELECT 1 FROM candidate_status_history h WHERE h.candidate_id=c.id)");
db.exec('CREATE UNIQUE INDEX IF NOT EXISTS documents_job_hash ON documents(job_id, file_hash)');

export type JobRow = { id: string; title: string; description: string; status: string; rubric_version: string; rubric: string|null; created_at: string; updated_at: string };
export type DocumentRow = { id:string; job_id:string; original_filename:string; stored_filename:string; file_path:string; file_hash:string; page_count:number|null; raw_text:string; normalized_text:string; processing_status:string; processing_error:string|null; created_at:string; updated_at:string; job_title?:string };
export type CandidateRow = {id:string;job_id:string;document_id:string;candidate_name:string|null;email:string|null;phone:string|null;location:string|null;summary:string|null;structured_data:string;extraction_status:string;extraction_error:string|null;current_status:string;status_updated_at:string;created_at:string;updated_at:string;original_filename?:string;normalized_text?:string;most_recent_position?:string|null};
export type FitReviewRow = {id:string;job_id:string;job_title:string|null;job_description:string;candidate_ids:string;evaluation_result:string;model_name:string;prompt_version:string;created_at:string};
export type CandidateStatusHistoryRow = {id:string;candidate_id:string;from_status:string|null;to_status:string;changed_at:string};
export type CandidateFitReviewRow = {id:string;job_id:string;candidate_id:string;job_description:string;rubric:string|null;score:number;rationale:string;evidence:string;strengths:string;gaps:string;model_name:string;prompt_version:string;created_at:string};
export const fileHash=(buffer:Buffer)=>crypto.createHash('sha256').update(buffer).digest('hex');
export function safeFilename(filename:string){const base=path.basename(filename).replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'resume.pdf';return base.toLowerCase().endsWith('.pdf')?base:`${base}.pdf`;}
export function listJobs(){return db.prepare('SELECT * FROM jobs ORDER BY created_at DESC').all() as unknown as JobRow[];}
export function getJob(id:string){return db.prepare('SELECT * FROM jobs WHERE id=?').get(id) as JobRow|undefined;}
export function createJob(input:{title:string;description:string;rubric?:string|null;status?:string}){const id=`job-${crypto.randomUUID()}`, time=now();db.prepare('INSERT INTO jobs (id,title,description,status,rubric_version,rubric,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').run(id,input.title,input.description,input.status||'Open','v1.0',input.rubric||null,time,time);return getJob(id)!;}
export function updateJob(id:string,input:{title?:string;description?:string;rubric?:string|null;status?:string}){const current=getJob(id);if(!current)return undefined;const time=now();db.prepare('UPDATE jobs SET title=?,description=?,rubric=?,status=?,updated_at=? WHERE id=?').run(input.title??current.title,input.description??current.description,input.rubric===undefined?current.rubric:input.rubric,input.status??current.status,time,id);return getJob(id)!;}
export function getDocument(id:string){return db.prepare('SELECT d.*, j.title as job_title FROM documents d JOIN jobs j ON j.id=d.job_id WHERE d.id = ?').get(id) as DocumentRow|undefined;}
export function listDocuments(jobId?:string){const query=jobId?'SELECT d.*, j.title as job_title FROM documents d JOIN jobs j ON j.id=d.job_id WHERE d.job_id=? ORDER BY d.created_at DESC':'SELECT d.*, j.title as job_title FROM documents d JOIN jobs j ON j.id=d.job_id ORDER BY d.created_at DESC';return (jobId?db.prepare(query).all(jobId):db.prepare(query).all()) as unknown as DocumentRow[];}
export function getCandidate(id:string){return db.prepare('SELECT c.*, d.job_id, d.original_filename, d.normalized_text FROM candidates c JOIN documents d ON d.id=c.document_id WHERE c.id=?').get(id) as CandidateRow|undefined;}
export function listCandidates(jobId?:string){const query=jobId?'SELECT c.*, d.job_id, d.original_filename, d.normalized_text, json_extract(c.structured_data, \'$.experience[0].title\') as most_recent_position FROM candidates c JOIN documents d ON d.id=c.document_id WHERE d.job_id=? ORDER BY c.created_at DESC':'SELECT c.*, d.job_id, d.original_filename, d.normalized_text, json_extract(c.structured_data, \'$.experience[0].title\') as most_recent_position FROM candidates c JOIN documents d ON d.id=c.document_id ORDER BY c.created_at DESC';return (jobId?db.prepare(query).all(jobId):db.prepare(query).all()) as unknown as CandidateRow[];}
export function getCandidates(ids:string[],jobId?:string){if(!ids.length)return [];const marks=ids.map(()=>'?').join(',');const suffix=jobId?' AND d.job_id=?':'';const params=jobId?[...ids,jobId]:ids;return db.prepare(`SELECT c.*, d.job_id, d.original_filename, d.normalized_text FROM candidates c JOIN documents d ON d.id=c.document_id WHERE c.id IN (${marks})${suffix}`).all(...params) as unknown as CandidateRow[];}
export function createDocument(input:{jobId:string;originalFilename:string;buffer:Buffer;pageCount:number;rawText:string;normalizedText:string;structuredData:CandidateStructuredData;extractionStatus?:string;extractionError?:string|null}){const hash=fileHash(input.buffer);const existing=db.prepare('SELECT id FROM documents WHERE job_id=? AND file_hash=?').get(input.jobId,hash) as {id:string}|undefined;if(existing)return {duplicate:true,documentId:existing.id};const id=`doc-${crypto.randomUUID()}`, stored=`${id}-${safeFilename(input.originalFilename)}`, filePath=path.join(uploadDir,stored), time=now();db.exec('BEGIN');try{fs.writeFileSync(filePath,input.buffer);db.prepare('INSERT INTO documents (id,job_id,original_filename,stored_filename,file_path,file_hash,page_count,raw_text,normalized_text,processing_status,processing_error,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,input.jobId,input.originalFilename,stored,filePath,hash,input.pageCount,input.rawText,input.normalizedText,'completed',null,time,time);const candidateId=`candidate-${crypto.randomUUID()}`, initialStatus=input.extractionStatus==='completed'?'ready_for_review':'uploaded';db.prepare('INSERT INTO candidates (id,document_id,candidate_name,email,phone,location,summary,structured_data,extraction_status,extraction_error,current_status,status_updated_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(candidateId,id,input.structuredData.candidate_name,input.structuredData.email,input.structuredData.phone,input.structuredData.location,input.structuredData.summary,JSON.stringify(input.structuredData),input.extractionStatus||'completed',input.extractionError||null,initialStatus,time,time,time);db.prepare('INSERT INTO candidate_status_history (id,candidate_id,from_status,to_status,changed_at) VALUES (?,?,?,?,?)').run(`status-${crypto.randomUUID()}`,candidateId,null,initialStatus,time);db.exec('COMMIT');return {duplicate:false,documentId:id,candidateId};}catch(error){db.exec('ROLLBACK');try{fs.unlinkSync(filePath)}catch{};throw error;}}
export function deleteDocument(id:string){const doc=getDocument(id);if(!doc)return false;db.prepare('DELETE FROM documents WHERE id=?').run(id);try{fs.unlinkSync(doc.file_path)}catch{};return true;}
export function deleteJob(id:string){const job=getJob(id);if(!job)return false;const documents=listDocuments(id);db.exec('BEGIN');try{db.prepare('DELETE FROM candidate_fit_reviews WHERE job_id=?').run(id);db.prepare('DELETE FROM fit_reviews WHERE job_id=?').run(id);db.prepare('DELETE FROM documents WHERE job_id=?').run(id);db.prepare('DELETE FROM jobs WHERE id=?').run(id);db.exec('COMMIT');for(const document of documents){try{fs.unlinkSync(document.file_path)}catch{}}return true;}catch(error){db.exec('ROLLBACK');throw error;}}
export function updateDocumentContent(id:string,input:{pageCount:number;rawText:string;normalizedText:string;structuredData:CandidateStructuredData;status:string;error?:string|null}){const time=now();db.prepare('UPDATE documents SET page_count=?,raw_text=?,normalized_text=?,processing_status=?,processing_error=?,updated_at=? WHERE id=?').run(input.pageCount,input.rawText,input.normalizedText,input.status,input.error||null,time,id);db.prepare('UPDATE candidates SET candidate_name=?,email=?,phone=?,location=?,summary=?,structured_data=?,extraction_status=?,extraction_error=?,updated_at=? WHERE document_id=?').run(input.structuredData.candidate_name,input.structuredData.email,input.structuredData.phone,input.structuredData.location,input.structuredData.summary,JSON.stringify(input.structuredData),input.status,input.error||null,time,id);return getDocument(id);}
export function saveFitReview(input:{jobId:string;jobTitle:string|null;jobDescription:string;candidateIds:string[];result:unknown;modelName:string}){const id=`fit-${crypto.randomUUID()}`;db.prepare('INSERT INTO fit_reviews (id,job_id,job_title,job_description,candidate_ids,evaluation_result,model_name,prompt_version,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,input.jobId,input.jobTitle,input.jobDescription,JSON.stringify(input.candidateIds),JSON.stringify(input.result),input.modelName,'candidate-fit-v1',now());return getFitReview(id)!;}
export function listFitReviews(jobId?:string){const query=jobId?'SELECT * FROM fit_reviews WHERE job_id=? ORDER BY created_at DESC':'SELECT * FROM fit_reviews ORDER BY created_at DESC';return (jobId?db.prepare(query).all(jobId):db.prepare(query).all()) as unknown as FitReviewRow[];}
export function getFitReview(id:string){return db.prepare('SELECT * FROM fit_reviews WHERE id=?').get(id) as FitReviewRow|undefined;}
export function updateCandidateStatus(id:string,status:string){const candidate=getCandidate(id);if(!candidate)return undefined;if(candidate.current_status===status)return candidate;const time=now();db.exec('BEGIN');try{db.prepare('UPDATE candidates SET current_status=?,status_updated_at=?,updated_at=? WHERE id=?').run(status,time,time,id);db.prepare('INSERT INTO candidate_status_history (id,candidate_id,from_status,to_status,changed_at) VALUES (?,?,?,?,?)').run(`status-${crypto.randomUUID()}`,id,candidate.current_status,status,time);db.exec('COMMIT');return getCandidate(id)!;}catch(error){db.exec('ROLLBACK');throw error;}}
export function listCandidateStatusHistory(candidateId:string){return db.prepare('SELECT * FROM candidate_status_history WHERE candidate_id=? ORDER BY changed_at ASC').all(candidateId) as unknown as CandidateStatusHistoryRow[];}
export function saveCandidateFitReview(input:{jobId:string;candidateId:string;jobDescription:string;rubric?:string|null;score:number;rationale:string;evidence:unknown;strengths:unknown;gaps:unknown;modelName:string;promptVersion:string}){const id=`candidate-fit-${crypto.randomUUID()}`;db.prepare('INSERT INTO candidate_fit_reviews (id,job_id,candidate_id,job_description,rubric,score,rationale,evidence,strengths,gaps,model_name,prompt_version,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,input.jobId,input.candidateId,input.jobDescription,input.rubric||null,input.score,input.rationale,JSON.stringify(input.evidence),JSON.stringify(input.strengths),JSON.stringify(input.gaps),input.modelName,input.promptVersion,now());return getCandidateFitReview(id)!;}
export function getCandidateFitReview(id:string){return db.prepare('SELECT * FROM candidate_fit_reviews WHERE id=?').get(id) as CandidateFitReviewRow|undefined;}
export function listCandidateFitReviews(candidateId:string){return db.prepare('SELECT * FROM candidate_fit_reviews WHERE candidate_id=? ORDER BY created_at DESC').all(candidateId) as unknown as CandidateFitReviewRow[];}
