import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';
const timestamps={createdAt:integer('created_at',{mode:'timestamp'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp'})};
export const jobs=sqliteTable('jobs',{id:text('id').primaryKey(),title:text('title').notNull(),description:text('description').notNull(),status:text('status').notNull(),...timestamps});
export const rubrics=sqliteTable('rubrics',{id:text('id').primaryKey(),jobId:text('job_id').notNull(),version:text('version').notNull(),criteriaJson:text('criteria_json').notNull(),createdAt:timestamps.createdAt});
export const candidates=sqliteTable('candidates',{id:text('id').primaryKey(),displayCode:text('display_code').notNull(),createdAt:timestamps.createdAt});
export const resumeDocuments=sqliteTable('resume_documents',{id:text('id').primaryKey(),candidateId:text('candidate_id').notNull(),originalFilename:text('original_filename').notNull(),mimeType:text('mime_type').notNull(),extractedText:text('extracted_text').notNull(),redactedText:text('redacted_text').notNull(),contentHash:text('content_hash').notNull(),createdAt:timestamps.createdAt});
export const reviewRuns=sqliteTable('review_runs',{id:text('id').primaryKey(),candidateId:text('candidate_id').notNull(),jobId:text('job_id').notNull(),rubricId:text('rubric_id').notNull(),provider:text('provider').notNull(),model:text('model'),promptVersion:text('prompt_version').notNull(),status:text('status').notNull(),overallScore:integer('overall_score'),evidenceBand:text('evidence_band'),startedAt:timestamps.createdAt,completedAt:integer('completed_at',{mode:'timestamp'}),errorMessage:text('error_message')});
export const criterionResults=sqliteTable('criterion_results',{id:text('id').primaryKey(),reviewRunId:text('review_run_id').notNull(),criterionKey:text('criterion_key').notNull(),score:integer('score').notNull(),confidence:integer('confidence').notNull(),rationale:text('rationale').notNull(),evidenceJson:text('evidence_json').notNull(),missingInformationJson:text('missing_information_json').notNull()});
export const humanReviews=sqliteTable('human_reviews',{id:text('id').primaryKey(),reviewRunId:text('review_run_id').notNull(),reviewerName:text('reviewer_name').notNull(),outcome:text('outcome').notNull(),notes:text('notes').notNull(),createdAt:timestamps.createdAt});
